# Generated by Django 4.2.3 on 2023-07-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(default='None'),
        ),
        migrations.AddField(
            model_name='client',
            name='useragent',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
